### ISSUE TITLE
init时内存溢出

### ISSUE THREAD

**Issue by Foooog** [bupticybee/TexasHoldemSolverJava#16]
initizing...
loading holdem compairer dictionary...
Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space
	at java.util.Hashtable.<init>(Unknown Source)
	at java.util.Hashtable.<init>(Unknown Source)
	at icybee.solver.compairer.Dic5Compairer.load_compairer(Dic5Compairer.java:37)
	at icybee.solver.compairer.Dic5Compairer.<init>(Dic5Compairer.java:31)
	at icybee.solver.SolverEnvironment.compairerFromConfig(SolverEnvironment.java:101)
	at icybee.solver.gui.SolverGui.load_compairer(SolverGui.java:107)
	at icybee.solver.gui.SolverGui.initize(SolverGui.java:229)
	at icybee.solver.gui.SolverGui.access$000(SolverGui.java:23)
	at icybee.solver.gui.SolverGui$1.run(SolverGui.java:303)

**Comment by bupticybee** [comment]
一般这种问题可能由两种问题引起：

- java版本问题，java需要是64位java，不可以是32位的
- 环境变量是否配置好？装的64位java是否正确的配置到环境变量里了？

你可以先尝试这两种方法

**Comment by bupticybee** [comment]
This issue is not active for a month, closing for now
