### ISSUE TITLE
打开程序后log报错

### ISSUE THREAD

**Issue by ZishengTong** [bupticybee/TexasHoldemSolverJava#24]
log提示下面报错是什么原因呢？（jre已经是11.0.2）
Exception in thread "Thread-0" java.lang.RuntimeException: load config failed: cannot find config file
	at icybee.solver.gui.SolverGui.loadConfig(SolverGui.java:100)
	at icybee.solver.gui.SolverGui.load_compairer(SolverGui.java:106)
	at icybee.solver.gui.SolverGui.initize(SolverGui.java:229)
	at icybee.solver.gui.SolverGui.access$000(SolverGui.java:23)
	at icybee.solver.gui.SolverGui$1.run(SolverGui.java:303)

**Comment by bupticybee** [comment]
你可以先在其他issue里边看一圈，基本每三个issue就有一个是这个问题，非常常见了，基本要不是java没装好，要不是安装路径有中文。

**Comment by bupticybee** [comment]
Closing because this issue is not active for 2 months,reopen if necessary.
