### ISSUE TITLE
run release project error， load config failed

### ISSUE THREAD

**Issue by mydaoyuan** [bupticybee/TexasHoldemSolverJava#6]
按照文档给出的链接安装了 [java re](https://www.oracle.com/java/technologies/javase-jre8-downloads.html)

release包版本为 TexasHoldemSolverJava 0.2.0

下载后启动 jar 包，log窗口出现以下报错

```
initizing...
loading holdem compairer dictionary...
Exception in thread "Thread-0" java.lang.RuntimeException: load config failed: cannot find config file
	at icybee.solver.gui.SolverGui.loadConfig(SolverGui.java:100)
	at icybee.solver.gui.SolverGui.load_compairer(SolverGui.java:106)
	at icybee.solver.gui.SolverGui.initize(SolverGui.java:229)
	at icybee.solver.gui.SolverGui.access$000(SolverGui.java:23)
	at icybee.solver.gui.SolverGui$1.run(SolverGui.java:303)

```

本地 Java 版本为

```
java --version
openjdk 11.0.10 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9)
OpenJDK 64-Bit Server VM (build 11.0.10+9, mixed mode)
```

-----

是需要进行什么配置文件进行配置吗？

**Comment by bupticybee** [comment]
这个报错的原因是程序没有找到资源文件，你是否把jar文件单独拿出运行？

正常的solver应该包含下面文件：

![image](https://user-images.githubusercontent.com/9393610/111294476-5634b800-8685-11eb-93c7-66a01886cb1a.png)

看下你的目录中是否有缺少

**Comment by bupticybee** [comment]
还需要知道你的具体操作系统

**Comment by mydaoyuan** [comment]
> 这个报错的原因是程序没有找到资源文件，你是否把jar文件单独拿出运行？
> 
> 正常的solver应该包含下面文件：
> 
> ![image](https://user-images.githubusercontent.com/9393610/111294476-5634b800-8685-11eb-93c7-66a01886cb1a.png)
> 
> 看下你的目录中是否有缺少

感谢回复。
目录没有缺少，看到你说资源文件缺失，我发现我的默认下载文件夹是中文，移动到英文文件夹下后正常运行了。
