### ISSUE TITLE
【打开报错求助】

### ISSUE THREAD

**Issue by Nemobkbmydb** [bupticybee/TexasHoldemSolverJava#9]
按照步骤安装了JRE和release包，运行时报错，调至全英文目录后仍然报错……
![image](https://user-images.githubusercontent.com/81156912/111974657-9a6b0100-8b3a-11eb-8b00-a534d5bcf0c2.png)
![image](https://user-images.githubusercontent.com/81156912/111974712-ace53a80-8b3a-11eb-95d4-af7bf75a2ee6.png)

**Comment by Nemobkbmydb** [comment]
报错信息：
Exception in thread "Thread-0" java.lang.RuntimeException: load config failed: cannot find config file
	at icybee.solver.gui.SolverGui.loadConfig(SolverGui.java:100)
	at icybee.solver.gui.SolverGui.load_compairer(SolverGui.java:106)
	at icybee.solver.gui.SolverGui.initize(SolverGui.java:229)
	at icybee.solver.gui.SolverGui.access$000(SolverGui.java:23)
	at icybee.solver.gui.SolverGui$1.run(SolverGui.java:303)

**Comment by bupticybee** [comment]
麻烦运行下java --version确定java版本，然后展示下所在目录结构

**Comment by Nemobkbmydb** [comment]
> java --version

![image](https://user-images.githubusercontent.com/81156912/111976476-a1930e80-8b3c-11eb-9bd1-c492e5c6e641.png)
![image](https://user-images.githubusercontent.com/81156912/111976572-bbccec80-8b3c-11eb-9601-4589b00a0b74.png)

**Comment by Nemobkbmydb** [comment]
> 麻烦运行下java --version确定java版本，然后展示下所在目录结构
java为64位，所在目录结构如图，看起来是正常的

**Comment by bupticybee** [comment]
不太应该呀，我这里看觉得所有配置都正确

**Comment by bupticybee** [comment]
尝试一下从iterm中启动是否正常？使用命令java -jar RiverSolver.jar

**Comment by Nemobkbmydb** [comment]
> 尝试一下从iterm中启动是否正常？使用命令java -jar RiverSolver.jar

刚用windows的机器尝试了，似乎还是报错；java版本信息、所在目录结构如图；尝试用cmd启动似乎仍报错；稍后再用mac尝试下；
报错信息：
Exception in thread "Thread-1" java.lang.OutOfMemoryError: Java heap space
	at java.util.Hashtable.<init>(Unknown Source)
	at java.util.Hashtable.<init>(Unknown Source)
	at icybee.solver.compairer.Dic5Compairer.load_compairer(Dic5Compairer.java:37)
	at icybee.solver.compairer.Dic5Compairer.<init>(Dic5Compairer.java:31)
	at icybee.solver.SolverEnvironment.compairerFromConfig(SolverEnvironment.java:101)
	at icybee.solver.gui.SolverGui.load_compairer(SolverGui.java:107)
	at icybee.solver.gui.SolverGui.initize(SolverGui.java:229)
	at icybee.solver.gui.SolverGui.access$000(SolverGui.java:23)
	at icybee.solver.gui.SolverGui$1.run(SolverGui.java:303)

![image](https://user-images.githubusercontent.com/81156912/112002757-31e04c00-8b5b-11eb-946f-60bf03fa8a4a.png)
![image](https://user-images.githubusercontent.com/81156912/112002831-44f31c00-8b5b-11eb-99da-9df4f1a8a069.png)
![image](https://user-images.githubusercontent.com/81156912/112002926-5ccaa000-8b5b-11eb-8466-a040d326af7f.png)

**Comment by Nemobkbmydb** [comment]
> 尝试一下从iterm中启动是否正常？使用命令java -jar RiverSolver.jar

这边在运行前只安装了JRE，会不会是还需要其他环境呢？

**Comment by Nemobkbmydb** [comment]
> 尝试一下从iterm中启动是否正常？使用命令java -jar RiverSolver.jar

Mac从iterm运行，可以正常使用&求解
![image](https://user-images.githubusercontent.com/81156912/112084874-7e13a680-8bc4-11eb-90a5-b2a25d94504e.png)
![image](https://user-images.githubusercontent.com/81156912/112084883-810e9700-8bc4-11eb-8081-e60c71201919.png)
![image](https://user-images.githubusercontent.com/81156912/112084889-84098780-8bc4-11eb-92f0-359e965225c0.png)
![image](https://user-images.githubusercontent.com/81156912/112084896-866be180-8bc4-11eb-92d3-dd7e936f2be1.png)

**Comment by bupticybee** [comment]
Ok,那暂时如此解决，后续这个bug我会记录并且尝试解决

**Comment by bupticybee** [comment]
暂时关闭issue
